spring.datasource.url=jdbc:postgresql://localhost:5432/ArticleLibrary
spring.datasource.username=postgres
spring.datasource.password=ImNotSharingItOnGit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=1247
